name: Build macOS DMG

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: npm install --save-dev @electron-forge/maker-dmg
      - run: npm run build

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: terabox-macos-app
          path: out/make/dmg/**/*.dmg
