name: Build macOS App (.dmg)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd electron
          npm install

      - name: Build .dmg using Electron Forge
        run: |
          cd electron
          npx electron-forge make --platform=darwin

      - name: Upload .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terabox-app-mac
          path: electron/out/make/**/*.dmg

          - name: Install missing makers
  run: |
    cd electron
    npm install --save-dev @electron-forge/maker-dmg @electron-forge/maker-zip

