name: Build Electron macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    # You can lock to macos-14 if you want to avoid the auto-upgrade to macOS 15
    # Or keep macos-latest for the newest available
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd electron
          npm install

      - name: Build Electron app for macOS (.app)
        run: |
          cd electron
          npx electron-packager . TeraBoxDrive --platform=darwin --arch=x64 --overwrite

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeraBoxDrive-macos-app
          path: electron/TeraBoxDrive-darwin-x64/TeraBoxDrive.app
