name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd electron
          npm install

      - name: Install Electron Forge makers
        run: |
          cd electron
          npm install --save-dev @electron-forge/maker-dmg @electron-forge/maker-zip

      - name: Build app
        run: |
          cd electron
          npm run make
